FROM python:3
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /
COPY trumio_ai_server/requirements.txt trumio_ai_server/
WORKDIR /trumio_ai_server
RUN pip install -r requirements.txt
COPY . /trumio_ai_server/